### ISSUE TITLE
[Bug] Rag based questions not working properly with links

### ISSUE THREAD

**Issue by srinarayan-srikanthan** [opea-project/GenAIExamples#1043]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

main branch

### Description

What is OPEA question after providing link : https://opea-project.github.io/latest/introduction/index.html is hallucinating but same question after uploading a PDF with same info working.

### Reproduce steps

readme from main

**Comment by yinghu5** [comment]
Hi Sri, 
Thank you for reporting the issue. The issue should be fixed in later release.
FYI： 
tried the link today with main branch using  https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker_compose/intel/cpu/xeon/README.md
open browser： http://{host_ip}:80
get the answer: 

![image](https://github.com/user-attachments/assets/3447d6f1-a40f-4088-8b04-9414a018959c)
