### ISSUE TITLE
urllib3.exceptions.MaxRetryError for localhost:4318 in ChatQnA services

### ISSUE THREAD

**Issue by Feelas** [opea-project/GenAIExamples#172]
I can see that GenAIComps includes a newly implemented OpenTelemetry support. Despite it looking like a necessity, there is not an OpenTelemetry service included in ChatQnA docker_compose, nor environment value "TELEMETRY_ENDPOINT" mentioned anywhere.

Is it a problem if we continue without the OpenTelemetry endpoint?

**Comment by Spycsh** [comment]
Hi @Feelas , we will add the document for OpenTelemetry soon. It is not a problem that you use your megaservice/microservices without OpenTelemetry endpoint, which means you can ignore those exceptions because they do not affect any usage of the mega/microservices. For now, if you want to use OpenTelemetry, please run the following commands to open the Jaeger dashboard

```
docker run -d --rm \
-e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
-p 16686:16686 \
-p 4317:4317 \
-p 4318:4318 \
-p 9411:9411 \
jaegertracing/all-in-one:latest
```

Then you can check the Jaeger dashboard with you web browser on `<ip address>:16686`.

**Comment by xiguiw** [comment]
@Feelas What's the status now?
Have you tried the way @Spycsh show you?

**Comment by Feelas** [comment]
Hello @xiguiw, thanks for asking. 

I didn't really have time to give it a good try. It is good enough for now to understand that the errors can be ignored if not really needed.

**Comment by xiguiw** [comment]
@Feelas Thanks for confirm this.

Close as no more action required.
