### ISSUE TITLE
LLM Microservice is throwing Internal Server Error

### ISSUE THREAD

**Issue by skuma31** [opea-project/GenAIExamples#372]
I am using charQnA in Xeon server and below are my running setup:

1. Running docker containers stack:
![Screenshot 2024-07-03 234730](https://github.com/opea-project/GenAIExamples/assets/60603468/65243ee0-1074-4dd6-a6e3-b405e343fded)

2.  LLM microservice query is throwing error " Internal Server Error"

![Screenshot 2024-07-03 235138](https://github.com/opea-project/GenAIExamples/assets/60603468/2f0e3535-71bb-43f9-a74d-655294ad3daa)

Please let me know if you need anything else.

**Comment by xiguiw** [comment]
@skuma31 
please check the log of the LLM microservice by this command `docker logs container-id`

1. There are several reasons for the "internal server error:
a. TGI server cannot be accessed by LLM microservice due to proxy
      Run `curl -vv http://${host_ip}:9000/v1/chat/completions\   -X POST `
      if the log is due to proxy connection. if YES, add you {host_ip} into no_proxy.
b. The TGI server is not ready. It needs to downloading model and warm up, it takes several minutes depends on you network bandwidth and model size and computing resources etc.

c. TGI server errors

Please follow the https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md#validate-microservices 
Make sure TGI server works well, then check LLM micro service next.

**Comment by skuma31** [comment]
Thank you @yinghu5 . The issue was due to Hugginface API token and now it is working. I will close this ticket.
