### ISSUE TITLE
Managed vector database example

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#411]
A lot of customers use managed Vector database service. The current examples demonstrate a Vector database as a bundled microservice. To address the SaaS customers, there is a need to have an example that uses a managed Vector database.

**Comment by endomorphosis** [comment]
There is already an example of managed vector database, for example postgres, its just that there is not a managed pinecone database.

https://github.com/opea-project/GenAIComps/tree/main/comps/vectorstores/langchain/pgvector

**Comment by arun-gupta** [comment]
I'm looking for an example to use a managed service, such as Pinecone or Zilliz or something similar.

**Comment by pallavijaini0525** [comment]
@arun-gupta  - have added implementations for the pinecone db.

dataprep - https://github.com/opea-project/GenAIComps/tree/main/comps/dataprep/pinecone
retriever - https://github.com/opea-project/GenAIComps/tree/main/comps/retrievers/langchain/pinecone
vector store - https://github.com/opea-project/GenAIComps/tree/main/comps/vectorstores/langchain/pinecone

**Comment by arun-gupta** [comment]
@pallavijaini0525 this is awesome. How do I use this with ChatQnA example?

**Comment by pallavijaini0525** [comment]
To use the pinecone DB, 

1. instead of redis DB docker up and running, create the Pinecone API key and the index creation -https://github.com/opea-project/GenAIComps/tree/main/comps/vectorstores/langchain/pinecone -> No need to run a docker container for Pinecone as Pinecone DB is in cloud.
2. for Retriever service and Dataprep services in ChatQnA use the pinecone Dockerfiles instead of redis to build the images.
3. In the docker compose make the necessary changes to use the pinecone images.

**Comment by arun-gupta** [comment]
This is helpful.

Can you contribute a Docker Compose file that allows developers to run this entire configuration?

**Comment by pallavijaini0525** [comment]
@arun-gupta  - Created the PR - https://github.com/opea-project/GenAIExamples/pull/540 and https://github.com/opea-project/GenAIComps/pull/420 to support Pinecone DB for the ChatQnA-

 Verified the full pipeline
