### ISSUE TITLE
Image in ChatQnA Flow Chart needs fixing

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#681]
With a black background, the arrows from Embedding to Embedding service are not visible outside the white box. Ditto with any arrows outside the white box.

Top right, there is a typo "Micrservice" instead of "Microservice".

User Interface box seems to be disproportionately bigger than the Megaservice box.

The left side of the image shows controls on top of the image. This hides the image details behind the control. This is shown below:

<img width="233" alt="image" src="https://github.com/user-attachments/assets/a33f1fea-d9d5-49fc-ade0-02dc57fb9b88">

Can the flowchart be published as PNG?

**Comment by wangkl2** [comment]
@louie-tsai Could you please take a look at the flowchart display issue of chatqna? Thanks.

**Comment by louie-tsai** [comment]
Start addressing the inputs in below branch.
https://github.com/intel-ai-tce/GenAIExamples/blob/issue_681/ChatQnA/README.md

@ctao456  

Could you help on below requests?

1. User Interface box seems to be disproportionately bigger than the Megaservice box. 
2. The left side of the image shows controls on top of the image. This hides the image details behind the control.

**Comment by ctao456** [comment]
@louie-tsai 
I was able to resolve both of the requests:
1. I put `direction LR` inside the legend subgraph, to change the overall graph layout
2. I further increased font by `themeVariables: fontSize: 76px` so that the text is more visible. The control buttons is an integrated github feature that cannot be changed.

Please refer to the updated flowchart here:
[https://github.com/ctao456/GenAIExamples/tree/ctao/fix_flowchart/ChatQnA](https://github.com/ctao456/GenAIExamples/tree/ctao/fix_flowchart/ChatQnA)

**Comment by louie-tsai** [comment]
@arun-gupta 
Addressed most of comments in below PR. 
https://github.com/opea-project/GenAIExamples/pull/736
Some limitation for the mermaid scripts, so couldn't address all feedbacks.

**Comment by arun-gupta** [comment]
Arrows are still invisible

<img width="1017" alt="image" src="https://github.com/user-attachments/assets/afff8feb-51ca-4171-b528-f49df612e39d">

May be we should use a different tool? Or use a PNG, like the image above?

**Comment by louie-tsai** [comment]
@arun-gupta 
No PNG. We want to make the diagram version control.  it is hard to collaborate with a PNG file.

moreover, why you have black background in your browser? 
In general, we have white background as below diagram, so you should be able to see the black arrow.
![image](https://github.com/user-attachments/assets/84d6d0f2-7746-4b3d-9431-868d9b1b1f0b)

**Comment by arun-gupta** [comment]
People use all different kinds of backgrounds. We need to be inclusive to provide right experience for the image.

**Comment by ctao456** [comment]
Hi @arun-gupta @louie-tsai ,

Please refer to the below updated flowchart. Deleted "theme" config so that color is automatic to black and white backgrounds by default.
[https://github.com/ctao456/GenAIExamples/tree/ctao/fix_flowchart/ChatQnA](https://github.com/ctao456/GenAIExamples/tree/ctao/fix_flowchart/ChatQnA
)

Light background:
![image](https://github.com/user-attachments/assets/4728e489-3f95-44b8-82ac-6c1ead6967af)

Dark background:
![image](https://github.com/user-attachments/assets/622f2782-229b-4f98-ad2a-fd2f84db690a)

**Comment by arun-gupta** [comment]
How wonderful, looks great!

**Comment by ctao456** [comment]
[like]  Tao, Chun reacted to your message:
________________________________

**Comment by louie-tsai** [comment]
fixed in the latest README
https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA

**Comment by louie-tsai** [comment]
fixed in the latest readme. let us know if any issue still exists
